using System;
using System.Collections.Generic;
using TTObjectClasses;

namespace AtlasModel
{
    public partial class LowerExtremity
    {
        public Guid ObjectId { get; set; }
        public string UE_HD_Myoelectric_Desc { get; set; }
        public string LE_CauseOfInjury { get; set; }
        public string LE_AmputationDate { get; set; }
        public string LE_ProsthesisNumber { get; set; }
        public string LE_ConstructionDate { get; set; }
        public string LE_ProstheticType { get; set; }
        public string UE_AmputationDate { get; set; }
        public string UE_CauseOfInjury { get; set; }
        public string UE_ConstructionDate { get; set; }
        public string UE_ProsthesisNumber { get; set; }
        public string UE_ProstheticType { get; set; }
        public string UE_HD_FunctionalMovement_Desc { get; set; }
        public YesNoEnum? UE_HD_StumpZone { get; set; }
        public string UE_HD_StumpZone_Desc { get; set; }
        public YesNoEnum? UE_HD_Contracture { get; set; }
        public string UE_HD_Contracture_Desc { get; set; }
        public YesNoEnum? UE_HD_Musculoskeletal { get; set; }
        public string UE_HD_Musculoskeletal_Desc { get; set; }
        public YesNoEnum? UE_HD_Neurological { get; set; }
        public string UE_HD_Neurological_Desc { get; set; }
        public YesNoEnum? UE_HD_Cardiovascular { get; set; }
        public string UE_HD_Cardiovascular_Desc { get; set; }
        public YesNoEnum? UE_HD_Pulmonary { get; set; }
        public string UE_HD_Pulmonary_Desc { get; set; }
        public YesNoEnum? UE_HD_OrganFailure { get; set; }
        public string UE_HD_OrganFailure_Desc { get; set; }
        public YesNoEnum? UE_HD_SystemicDisease { get; set; }
        public string UE_HD_SystemicDisease_Desc { get; set; }
        public YesNoEnum? UE_HD_Myoelectric { get; set; }
        public string UE_SK_ProstheticType { get; set; }
        public string LE_SK_ProstheticType { get; set; }
        public string UE_HD_PreferencePetition_Desc { get; set; }
        public string UE_HD_SufficientStump_Desc { get; set; }
        public YesNoEnum? LE_MedicalReason { get; set; }
        public YesNoEnum? LE_ThirdStepHealthInst { get; set; }
        public YesNoEnum? LE_FTRExpertApprove { get; set; }
        public YesNoEnum? LE_OrthopedicExpertApprove { get; set; }
        public YesNoEnum? LE_PsychiatricExpertApprove { get; set; }
        public YesNoEnum? LE_HeadDoctorApprove { get; set; }
        public YesNoEnum? LE_PatientNameSurname { get; set; }
        public YesNoEnum? LE_MedulaInsCode { get; set; }
        public YesNoEnum? LE_Date { get; set; }
        public YesNoEnum? LE_MedulaOrProtocolNo { get; set; }
        public YesNoEnum? LE_DiagnosAndICD10Code { get; set; }
        public YesNoEnum? LE_MachineName { get; set; }
        public YesNoEnum? LE_MachineNameIsCorrect { get; set; }
        public YesNoEnum? LE_WetSignature { get; set; }
        public string LE_HD_AktivityLevel { get; set; }
        public YesNoEnum? LE_HD_PreferencePetition { get; set; }
        public YesNoEnum? LE_HD_StumpZone { get; set; }
        public YesNoEnum? LE_HD_WeightTolerance { get; set; }
        public YesNoEnum? LE_HD_Contracture { get; set; }
        public YesNoEnum? LE_HD_SingleSideAmputate { get; set; }
        public YesNoEnum? LE_HD_Ambulation { get; set; }
        public YesNoEnum? LE_HD_Musculoskeletal { get; set; }
        public YesNoEnum? LE_HD_Neurological { get; set; }
        public YesNoEnum? LE_HD_Cardiovascular { get; set; }
        public YesNoEnum? LE_HD_Pulmonary { get; set; }
        public YesNoEnum? LE_HD_OrganFailure { get; set; }
        public YesNoEnum? LE_HD_SystemicDisease { get; set; }
        public string LE_TEM_WhichLevel { get; set; }
        public YesNoEnum? LE_TEM_OscillationandPosture { get; set; }
        public YesNoEnum? LE_TEM_WalkingSpeed { get; set; }
        public YesNoEnum? LE_TEM_StrideLength { get; set; }
        public YesNoEnum? LE_TEM_StepClimbing { get; set; }
        public YesNoEnum? LE_TEM_WalkBackwards { get; set; }
        public YesNoEnum? LE_TEM_Waterproof { get; set; }
        public string LE_HD_Ambulation_Desc { get; set; }
        public string LE_HD_Cardiovascular_Desc { get; set; }
        public string LE_HD_Contracture_Desc { get; set; }
        public string LE_HD_Musculoskeletal_Desc { get; set; }
        public string LE_HD_Neurological_Desc { get; set; }
        public string LE_HD_OrganFailure_Desc { get; set; }
        public string LE_HD_PreferencePetition_Desc { get; set; }
        public string LE_HD_Pulmonary_Desc { get; set; }
        public string LE_HD_SingleSideAmputate_Desc { get; set; }
        public string LE_HD_StumpZone_Desc { get; set; }
        public string LE_HD_SystemicDisease_Desc { get; set; }
        public string LE_HD_WeightTolerance_desc { get; set; }
        public string LE_TEM_Oscillationand_Desc { get; set; }
        public string LE_TEM_StepClimbing_Desc { get; set; }
        public string LE_TEM_StrideLength_Desc { get; set; }
        public string LE_TEM_WalkBackwards_Desc { get; set; }
        public string LE_TEM_WalkingSpeed_Desc { get; set; }
        public string LE_TEM_Waterproof_Desc { get; set; }
        public YesNoEnum? UE_SK_MedicalReason { get; set; }
        public YesNoEnum? UE_SK_FTRExpertApprove { get; set; }
        public YesNoEnum? UE_SK_HeadDoctorApprove { get; set; }
        public YesNoEnum? UE_SK_OrthopedicExpApprove { get; set; }
        public YesNoEnum? UE_SK_PsychiatricExpApprove { get; set; }
        public YesNoEnum? UE_SK_sEMG { get; set; }
        public YesNoEnum? UE_SK_ThirdStepHealthInst { get; set; }
        public YesNoEnum? UE_RI_PatientNameSurname { get; set; }
        public YesNoEnum? UE_RI_MedulaInsCode { get; set; }
        public YesNoEnum? UE_RI_Date { get; set; }
        public YesNoEnum? UE_RI_MedulaOrProtocolNo { get; set; }
        public YesNoEnum? UE_RI_MachineName { get; set; }
        public YesNoEnum? UE_RI_DiagnosAndICD10Code { get; set; }
        public YesNoEnum? UE_RI_MachineNameIsCorrect { get; set; }
        public YesNoEnum? UE_RI_WetSignature { get; set; }
        public string UE_HD_AmputationLevel { get; set; }
        public int? UE_HD_StumpLength { get; set; }
        public YesNoEnum? UE_HD_PreferencePetition { get; set; }
        public YesNoEnum? UE_HD_SufficientStumpLength { get; set; }
        public YesNoEnum? UE_HD_SingleSideAmputate { get; set; }
        public string UE_HD_SingleSideAmputate_Desc { get; set; }
        public YesNoEnum? UE_HD_FunctionalMovements { get; set; }
        public string ATS_CauseOfInjury { get; set; }
        public string ATS_ChairNumber { get; set; }
        public string ATS_DeliveryDate { get; set; }
        public string ATS_ChairType { get; set; }
        public string ATS_SK_ChairType { get; set; }
        public string ATS_SK_MedicalReason { get; set; }
        public YesNoEnum? ATS_SK_ThirdStepHealthInst { get; set; }
        public YesNoEnum? ATS_SK_FTRExpertApprove { get; set; }
        public YesNoEnum? ATS_SK_OrthopedicExpApprove { get; set; }
        public YesNoEnum? ATS_SK_HeadDoctorApprove { get; set; }
        public YesNoEnum? ATS_RI_Date { get; set; }
        public YesNoEnum? ATS_RI_DiagnosAndICD10Code { get; set; }
        public YesNoEnum? ATS_RI_MachineName { get; set; }
        public YesNoEnum? ATS_RI_MedulaInsCode { get; set; }
        public YesNoEnum? ATS_RI_MedulaOrProtocolNo { get; set; }
        public YesNoEnum? ATS_RI_PatientNameSurname { get; set; }
        public YesNoEnum? ATS_RI_WetSignature { get; set; }
        public string ATS_HD_ChairDistance { get; set; }
        public bool? ATS_HD_INTRACOMMUNITY { get; set; }
        public bool? ATS_HD_Therapeutic { get; set; }
        public bool? ATS_HD_NOAMBULATION { get; set; }
        public YesNoEnum? ATS_HD_USELOWEREXTREMITIES { get; set; }
        public string ATS_HD_UseLowerExtremity_Desc { get; set; }
        public YesNoEnum? ATS_HD_ConstantCondition { get; set; }
        public YesNoEnum? ATS_HD_ChairModel { get; set; }
        public YesNoEnum? ATS_HD_UseHimself { get; set; }
        public YesNoEnum? ATS_HD_Deformity { get; set; }
        public YesNoEnum? ATS_HD_Contracture { get; set; }
        public YesNoEnum? ATS_HD_Cardiovascular { get; set; }
        public YesNoEnum? ATS_HD_Pulmonary { get; set; }
        public YesNoEnum? ATS_HD_OrganFailure { get; set; }
        public string ATS_HD_ConstantCondition_Desc { get; set; }
        public string ATS_HD_ChairModel_Desc { get; set; }
        public string ATS_HD_UseHimself_Desc { get; set; }
        public string ATS_HD_Deformity_Desc { get; set; }
        public string ATS_HD_Contracture_Desc { get; set; }
        public string ATS_HD_Cardiovascular_Desc { get; set; }
        public string ATS_HD_Pulmonary_Desc { get; set; }
        public string ATS_HD_OrganFailure_Desc { get; set; }

        #region Base Object Navigation Property
        public virtual BaseHCExaminationDynamicObject BaseHCExaminationDynamicObject { get; set; }
        #endregion Base Object Navigation Property
    }
}