
using System;
using System.Xml;
using System.Data;
using System.Text;
using System.Drawing;
using System.Reflection;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Collections.ObjectModel;
using System.Runtime.InteropServices;

using TTUtils;
using TTObjectClasses;
using TTDataDictionary;
using TTCoreDefinitions;
using TTConnectionManager;
using TTInstanceManagement;
using TTDefinitionManagement;
using TTStorageManager.Security;

using TTStorageManager;
using System.Runtime.Versioning;
using System.Windows.Forms;
using TTVisual;
namespace TTFormClasses
{
    public partial class InvoiceCollectionBoundForm : TTForm
    {
    /// <summary>
    /// İcmal
    /// </summary>
        protected TTObjectClasses.InvoiceCollection _InvoiceCollection
        {
            get { return (TTObjectClasses.InvoiceCollection)_ttObject; }
        }

        protected ITTLabel ttlabel1;
        protected ITTTextBox txtLastStateUser;
        protected ITTTextBox NameResource;
        protected ITTTextBox SendingNo;
        protected ITTTextBox Note;
        protected ITTTextBox No;
        protected ITTTextBox Name;
        protected ITTTextBox Description;
        protected ITTTextBox tttextbox1;
        protected ITTEnumComboBox ttenumcombobox1;
        protected ITTCheckBox chkIsGeneral;
        protected ITTLabel lblBatchInvoice;
        protected ITTGrid ttgrid1;
        protected ITTDateTimePickerColumn OPENINGDATE;
        protected ITTTextBoxColumn PATIENTFULLNAME;
        protected ITTTextBoxColumn EPISODENO;
        protected ITTTextBoxColumn UNIQUEREFNO;
        protected ITTTextBoxColumn PRICE;
        protected ITTTextBoxColumn INVOICEDATE;
        protected ITTTextBoxColumn INVOICENO;
        protected ITTLabel labelDeliveredDate;
        protected ITTDateTimePicker DeliveredDate;
        protected ITTLabel labelSendingDate;
        protected ITTDateTimePicker SendingDate;
        protected ITTLabel labelInvoiceTerm;
        protected ITTObjectListBox InvoiceTerm;
        protected ITTLabel labelProvizyonTipi;
        protected ITTObjectListBox ProvizyonTipi;
        protected ITTLabel labelTedaviTuru;
        protected ITTObjectListBox TedaviTuru;
        protected ITTLabel labelTedaviTipi;
        protected ITTObjectListBox TedaviTipi;
        protected ITTLabel labelPayer;
        protected ITTObjectListBox ttobjectlistbox1;
        protected ITTLabel labelTakipTipi;
        protected ITTObjectListBox TakipTipi;
        protected ITTLabel labelNameResource;
        protected ITTLabel labelSendingNo;
        protected ITTLabel labelNote;
        protected ITTLabel labelNo;
        protected ITTLabel labelName;
        protected ITTLabel labelLastStateDate;
        protected ITTDateTimePicker LastStateDate;
        protected ITTCheckBox IsAutoGenerated;
        protected ITTLabel labelDescription;
        protected ITTLabel labelDate;
        protected ITTDateTimePicker Date;
        protected ITTLabel labelCapacity;
        override protected void InitializeControls()
        {
            ttlabel1 = (ITTLabel)AddControl(new Guid("7c6c878e-0ae5-4ac2-beae-d8ba69a80476"));
            txtLastStateUser = (ITTTextBox)AddControl(new Guid("7ce4b1e0-0b70-437e-b356-087b40dc8f83"));
            NameResource = (ITTTextBox)AddControl(new Guid("0b576ba4-3069-4b7f-bcf5-23ff49dc23b5"));
            SendingNo = (ITTTextBox)AddControl(new Guid("1194dccf-4249-4b94-aa3e-637c258840e5"));
            Note = (ITTTextBox)AddControl(new Guid("9a7a5b92-ac2d-4c94-8d96-984642138419"));
            No = (ITTTextBox)AddControl(new Guid("881a979d-e6c0-4a1e-9e69-e3480a94bb8b"));
            Name = (ITTTextBox)AddControl(new Guid("c0decaa0-455e-4076-bcd0-52c71a2ee2e7"));
            Description = (ITTTextBox)AddControl(new Guid("3f5eee5c-651b-4bb7-a611-9a559aea638d"));
            tttextbox1 = (ITTTextBox)AddControl(new Guid("29b76b98-d741-4c8a-beb0-3ddca51894fa"));
            ttenumcombobox1 = (ITTEnumComboBox)AddControl(new Guid("eb35ed9c-f6b2-476c-b8c5-76161ae0a1f8"));
            chkIsGeneral = (ITTCheckBox)AddControl(new Guid("ae9453a2-df44-4f1e-ad97-0770707f2378"));
            lblBatchInvoice = (ITTLabel)AddControl(new Guid("d1bfaf27-45fa-497e-a838-9d1bae1c9f9f"));
            ttgrid1 = (ITTGrid)AddControl(new Guid("2a14fb9a-afab-4553-bd11-cbb29a4a417c"));
            OPENINGDATE = (ITTDateTimePickerColumn)AddControl(new Guid("23e3b4f1-cbbc-43c8-9570-57598d5a284c"));
            PATIENTFULLNAME = (ITTTextBoxColumn)AddControl(new Guid("ff00d71f-becb-431d-9e50-122ca9619f7f"));
            EPISODENO = (ITTTextBoxColumn)AddControl(new Guid("92535744-6693-4120-8e87-62dea78260eb"));
            UNIQUEREFNO = (ITTTextBoxColumn)AddControl(new Guid("78b0a32a-9e17-43f4-9cc0-9ffb17761a46"));
            PRICE = (ITTTextBoxColumn)AddControl(new Guid("5f546d9b-66d6-4397-9217-fef1099062b9"));
            INVOICEDATE = (ITTTextBoxColumn)AddControl(new Guid("cf597b28-9f6f-4634-8b00-469202716678"));
            INVOICENO = (ITTTextBoxColumn)AddControl(new Guid("691dc26b-70fe-4762-99f2-507f73df2fa9"));
            labelDeliveredDate = (ITTLabel)AddControl(new Guid("eca800f1-cb71-462a-a6a4-c6432d228bdf"));
            DeliveredDate = (ITTDateTimePicker)AddControl(new Guid("613d2b5a-1012-422d-b125-4785cc255c30"));
            labelSendingDate = (ITTLabel)AddControl(new Guid("5ddf5056-cc31-492d-ac4c-94156ffe25af"));
            SendingDate = (ITTDateTimePicker)AddControl(new Guid("8eb08adc-fbf4-48fe-a061-551cfeb2787a"));
            labelInvoiceTerm = (ITTLabel)AddControl(new Guid("564311c9-583d-45ae-b801-eddc732749e1"));
            InvoiceTerm = (ITTObjectListBox)AddControl(new Guid("e96630b2-4182-488b-bb46-04487dc576bf"));
            labelProvizyonTipi = (ITTLabel)AddControl(new Guid("c03d370a-2455-4d78-842a-db3bdc7e02e4"));
            ProvizyonTipi = (ITTObjectListBox)AddControl(new Guid("0a3ee8e5-099e-4f92-90a0-bb96b3228be2"));
            labelTedaviTuru = (ITTLabel)AddControl(new Guid("112f64c6-c4c8-41ee-8589-8b6fdda5322e"));
            TedaviTuru = (ITTObjectListBox)AddControl(new Guid("858cc5db-1fba-4808-8002-ca4ffd9f2404"));
            labelTedaviTipi = (ITTLabel)AddControl(new Guid("b3f0ae26-0f1f-4e85-aa73-34ed75b2392c"));
            TedaviTipi = (ITTObjectListBox)AddControl(new Guid("e3703ce8-42b2-40a5-b5a3-4f810886475f"));
            labelPayer = (ITTLabel)AddControl(new Guid("216d021a-23ea-4ae5-ba6a-ed712778ca48"));
            ttobjectlistbox1 = (ITTObjectListBox)AddControl(new Guid("83c67f4a-bf4b-4489-a09c-0b51a6b44fd0"));
            labelTakipTipi = (ITTLabel)AddControl(new Guid("fd9e12d3-13f1-494c-9cc2-d3584a9500ab"));
            TakipTipi = (ITTObjectListBox)AddControl(new Guid("1200417f-ed4d-4877-bf34-4c06bcc6a1ed"));
            labelNameResource = (ITTLabel)AddControl(new Guid("9d940371-0e07-45c0-88ef-ee32bf8de7d7"));
            labelSendingNo = (ITTLabel)AddControl(new Guid("aef4cd16-d0cf-4556-bad8-d8f14aca15df"));
            labelNote = (ITTLabel)AddControl(new Guid("d2c3f4a7-d9cb-4da2-b8b0-26e1e851845b"));
            labelNo = (ITTLabel)AddControl(new Guid("206bc6da-0b7f-4460-8db4-3e2a52fb1afe"));
            labelName = (ITTLabel)AddControl(new Guid("b90e9a00-c128-4ce3-84a6-4c891ef3ca32"));
            labelLastStateDate = (ITTLabel)AddControl(new Guid("0761bab6-78e4-4e47-bbb0-8bb422a15901"));
            LastStateDate = (ITTDateTimePicker)AddControl(new Guid("8bce0073-1478-4c35-a98f-6728ebbf924d"));
            IsAutoGenerated = (ITTCheckBox)AddControl(new Guid("fa2d9150-04b9-4f32-afe9-8d7cabf49de1"));
            labelDescription = (ITTLabel)AddControl(new Guid("33b5d18d-3a35-45cc-80d8-8ddf2a5ccf5a"));
            labelDate = (ITTLabel)AddControl(new Guid("8c891f7c-b8d0-4863-9fa4-b065998acb15"));
            Date = (ITTDateTimePicker)AddControl(new Guid("3c2559d3-8b2e-4c04-adf4-52cb4f7f65f0"));
            labelCapacity = (ITTLabel)AddControl(new Guid("8b146863-3248-47e3-a5f4-df8836e7404e"));
            base.InitializeControls();
        }

        public InvoiceCollectionBoundForm() : base("INVOICECOLLECTION", "InvoiceCollectionBoundForm")
        {
        }

        protected InvoiceCollectionBoundForm(string objectDefName, string formDefName) : base(objectDefName, formDefName)
        {
        }
    }
}