namespace TTObjectClasses
{
    public enum UserOptionType : int
    {
        Type1 = 0,
        Type2 = 1,
        PatientInfoFormClassic = 2,
        PatientInfoFormList = 3,
        MainHospitalForm = 4,
        PatientFolderControlGridActions = 5,
        PatientFolderControlGridEpisodes = 6,
        PatientFolderTreeControlGrid = 7,
        MessageFolderFormInbox = 8,
        MessageFolderFormSentItems = 9,
        MessageFolderFormDrafts = 10,
        AutoText = 11,
        QuickMenuAccess = 12,
        WorkListStartDate = 13,
        MessagingType = 14,
        JobListType = 15,
        WorkListEndDate = 16,
        DefaultAppointmentDefinition = 17,
        StockCardInfoFormClassic = 18,
        StockCardFolderControlStockTransactionsGrid = 19,
        ICDFilter = 20,
        UseMainPatientGroup = 21,
        PatientInfoFormDefault = 22,
        ShowChoosePatientGroupWaring = 23,
        WorkListColumnDefinition = 24,
        DoNotFillInpatientEpisodeSubactionsAndEpisodeActions = 25,
        OLAPThema = 26,
        OpeningScreenModuleSelection = 27,
        SelectedOutPatientResource = 28,
        SelectedInPatientResource = 29,
        SelectedSecMasterResource = 30,
        SelectedQueue = 31,
        FilterProcedureAndTests = 32,
        OrthesisWorklistSearchFilter = 33,
        FavoriteMenuItem = 34,
        UserBarcodeSettings = 35,
        StockMenu = 36,
        StockMenuPin = 37,
        HealthCommitteTemplate = 38
    }
}