namespace TTObjectClasses
{
    public enum AdmissionTypeEnum : int
    {
        Examination = 0,
        DoubleExamination = 1,
        HealthCommitteeExamination = 2,
        PeriodicExamination = 3,
        FollowUpExamination = 4,
        SecondFollowUpExamination = 5,
        ExcusedOf = 6,
        EndOfExcuse = 7,
        MovingToAnotherClimateForMedicalReasons = 8,
        EndOfMovingToAnotherClimateForMedicalReasons = 9,
        OnVacation = 10,
        Emergency = 11,
        AlcoholStorkeExamination = 12,
        NewBorn = 13,
        PortorExamination = 14,
        Arrested = 15,
        JudicialObservation = 16,
        Ex = 17,
        TemporaryHealthCommitteExamination = 18,
        AbroadDuty = 19,
        Investigation = 20,
        Manipulation = 21,
        InpatientAdmission = 24,
        DeathSuspicion = 25,
        Dispensary = 26,
        HealthCommitteeOfProffesors = 27,
        Surgery = 28,
        Dialysis = 30,
        Physiotheraphy = 31,
        HyperbaricOxygenTreatment = 32,
        ConsultationFromOtherHospitalRequestAcception = 33,
        SpacialCareExamReport = 34,
        DispatchFromOtherHospital = 35,
        InternalProcedureAdmission = 36,
        JudicialObservationFileInvestigation = 37,
        MaterialAdmission = 38,
        HealthCommiteeFromOtherHospitalRequest = 39,
        JudicialMedicineAdmission = 40,
        Daily = 41,
        HealthCommitteeExaminationFromOtherHospitalsRequestAcception = 42,
        DeadBorn = 43,
        PeriodicExaminationBrowsing = 44,
        ExternalReportApproval = 45,
        TrafficAccident = 46,
        ExceptionalState = 47
    }
}