namespace TTObjectClasses
{
    public enum AnesthesiaTechniqueEnum : int
    {
        Bolgesel = 0,
        Epidural = 1,
        EpiduralKatater = 2,
        Genel = 3,
        GenelEpidural = 4,
        GenelSpinal = 5,
        KombineSpinalEpidural = 6,
        Lokal = 7,
        Riva = 8,
        Sedoanaljezi = 9,
        Spinal = 10,
        SpinalKatater = 11,
        SinirBlokajı = 12,
        Tiva = 13,
        BolgeselEpidural = 14,
        BolgeselTiva = 15,
        BolgeselGenel = 16,
        BolgeselSpinal = 17,
        BolgeselLokal = 18,
        BolgeselRiva = 19,
        BolgeselSedoanaljezi = 20,
        BolgeselSinirBlokajı = 21,
        EpiduralTiva = 22,
        EpiduralLokal = 23,
        EpiduralRiva = 24,
        EpiduralSedoanaljezi = 25,
        EpiduralSinirBlokajı = 26,
        TivaGenel = 27,
        TivaSpinal = 28,
        TivaLokal = 29,
        TivaRiva = 30,
        TivaSedoanaljezi = 31,
        TivaSinirBlokajı = 32,
        GenelLokal = 33,
        GenelRiva = 34,
        GenelSedoanaljezi = 35,
        GenelSinirBlokajı = 36,
        LokalRiva = 37,
        LokalSedoanaljezi = 38,
        LokalSinirBlokajı = 39,
        RivaSedoanaljezi = 40,
        RivaSinirBlokajı = 41,
        SedoanaljeziSinirBlokajı = 42
    }
}