namespace TTObjectClasses
{
    public enum InvoiceOperationTypeEnum : int
    {
        Genel = 0,
        BasvuruOku = 1,
        TakipAl = 2,
        TakipOku = 3,
        TakipSil = 4,
        UpdateTedaviTipi = 5,
        UpdateProvizyonTipi = 6,
        UpdateTedaviTuru = 7,
        UpdateTakipTipi = 8,
        OzelDurumDegistir = 9,
        HizmetKayit = 10,
        HizmetSil = 11,
        HizmetOku = 12,
        Faturalandir = 13,
        FaturaTutarOku = 14,
        FaturaSil = 15,
        FaturaOku = 16,
        HastaCikisKayit = 17,
        HastaCikisIptal = 18,
        HastaCikisOku = 19,
        XXXXXXMedulaTakipGuncelle = 20,
        XXXXXXMedulaFazlaTakipAra = 21,
        FaturaOkuveBilgileriGuncelle = 22,
        GetRule = 23,
        GetLastRule = 24,
        CopySEP = 25,
        CancelSEP = 26,
        ExecRule = 27,
        IcmaleEkle = 28,
        IcmaldenCikar = 29,
        AddNewProcedure = 30,
        UpdateTrxState = 31,
        UpdateTrxInclusion = 32,
        UpdateTrxDate = 33,
        UpdateTrxSEP = 34,
        UpdateTrxOzelDurum = 35,
        UpdateTrxAmount = 36,
        UpdateTrxDoctor = 37,
        UpdateTrxSatinAlmaTarihi = 38,
        UpdateTrxBorcode = 39,
        UpdateTrxFirmaNo = 40,
        AddNewDiagnosis = 41,
        ChangePayer = 42,
        UpdateTrxUnitPrice = 43,
        UpdateMedulaReportNo = 44,
        UpdateTrxKesi = 45,
        SecerekFaturalandir = 46,
        UpdateSEPProperties = 47,
        UpdateTrxAccessionNo = 48,
        UpdateTrxDealerNo = 49,
        UXXXXXXullanimKesinlestirme = 50,
        UXXXXXXullanimKesinlestirmeIptal = 51,
        BagliTakipBilgisiKopar = 52,
        UpdateTrxPosition = 53,
        DokumanKaydet = 54,
        DokumanSil = 55,
        UpdateDiagnosisState = 56
    }
}