import { Guid } from 'NebulaClient/Mscorlib/Guid';
import { EyeColorEnum } from "./EyeColorEnum";
import { BeneficiaryEnum } from "./BeneficiaryEnum";
import { YesNoEnum } from "./YesNoEnum";
import { MainPatientGroupEnum } from "./MainPatientGroupEnum";
import { PatientGroupEnum } from "./PatientGroupEnum";
import { Person } from "./Person";


export class Patient extends Person {
    public Length: string;
    public MobilePhone: string;
    public LastNominationDate: Date;
    public EyeColor: EyeColorEnum;
    public EmploymentRecordid: string;
    public Cadre: string;
    public MPVTSourceTable: string;
    public PatientHistory: Object;
    public HomePhone: string;
    public WarVetera: boolean;
    public Disabled: boolean;
    public DemobilizationReason: string;
    public Habits: Object;
    public Class: string;
    public BloodGroupType: Object;
    public SpecialStatus: string;
    public IsRelativeOfSoldier: boolean;
    public WarVeteraCardNo: string;
    public Beneficiary: BeneficiaryEnum;
    public ImportantPatientInfo: Object;
    public RetirementFundID: string;
    public BeneficiaryDate: Date;
    public MilitaryEducationNo: string;
    public OYAKNO: string;
    public RelationshipID: number;
    public HomeAddress: string;
    public Deleted: YesNoEnum;
    public MainPatientGroup: MainPatientGroupEnum;
    public HOFEmploymentRecordID: string;
    public OldID: number;
    public HealtSlipNumber: string;
    public HomePostcode: string;
    public FirstNominationDate: Date;
    public Death: boolean;
    public Alive: boolean;
    public LastUpdateSiteGuid: Guid;
    public MPVTSourceID: string;
    public Photo: Object;
    public UnIdentified: boolean;
    public DemobilizationTime: Date;
    public DisabledWarVetera: boolean;
    public MilitaryAcceptanceTime: Date;
    public BagKurNo: string;
    public HeadOfFamilyUniqueRefNo: string;
    public PatientNameExtension: string;
    public ConscriptionPeriod: string;
    public ID: number;
    public Martyr: boolean;
    public EntryTime: Date;
    public PatientGroup: PatientGroupEnum;
    public ExciseNo: string;
    public EMail: string;
    public Note: string;
    public NotRequiredQuota: boolean;
    public Foreign: boolean;
    public SskNo: string;
    public PistolNo: string;
    public MPVTID: number;
    public PrivacyName: string;
    public PrivacySurname: string;
    public MPVTStatus: string;
    public MPVTHakShpDrm: string;
    public YUPASSNO: number;
    public Privacy: boolean;
    public PrivacyEndDate: Date;
    public PrivacyReason: string;
    public GenealogicalTree: Object;
    public Heigth: number;
    public Weight: number;
    public ChestCircumference: number;
    public HeadCircumference: number;
    public SecurePerson: boolean;
    public EducationStatus: string;
    public HOFHealtSlipNumber: string;
    public ContinuousDrugs: Object;
    public MilitaryNo: string;
    public BirthOrder: Object;
    public LastEHRUpdateDate: Date;
    public PatientFamilyHistory: Object;
    public HeadOfFamilyName: string;
    public Academy: string;
    public AgreementEndDate: Date;
    public IsNewBorn: boolean;
    public DeletedFromMPVT: boolean;
    public HOFRetirementFundID: string;
    public MPVTUpdateDate: Date;
    public LastUpdateRealSiteGuid: Guid;
    public PatientIDandFullName: string;
    public Age: number;
    public FullName: string;
    public RefNo: string;
    public AgeDay: number;
    public AgeMonth: number;
    public SubStringOfName: string;
    public FullAddress: string;
    public AgeCompleted: number;
    public IsPatientPrivacy: boolean;
}
