namespace TTObjectClasses
{
    public enum MKYS_ECikisStokHareketTurEnum : int
    {
        ckAmbarlarArasiDevir = 0,
        ckFireZayiat = 1,
        ckDevirDigerBirimlereCikis = 2,
        ckTuketim = 3,
        ckDevirKurumDisiMalzemeCikis = 4,
        ckTerkin = 5,
        ckSatis = 6,
        ckSayimNoksani = 7,
        ckYabanciUlkelereBagis = 8,
        ckKullanilmazHaleGelmeYokOlma = 9,
        ckHurdayaAyirma = 10,
        ckDonerSermayedenDevir = 11,
        ckDuzeltme = 12,
        ckTakas = 13,
        ckDevirIhtiyacFazlasiDevir = 14,
        ckDevirStokFazlasiDevir = 15,
        ckSatinalmasiBaglananXXXXXXCikisi = 16,
        ckXXXXXXBirlesmesindenDevir = 17,
        ckBagliBirimlereCikis = 18,
        ckTemelSagligaDevir = 19,
        ckKullanimaVermeKisi = 20,
        ckKullanimaVermeOrtakAlan = 21,
        ckIhtiyacFazlasi = 22,
        ckIhtiyacFazlasiIade = 23,
        ckZimmettenIade = 24,
        ckAfetDurumuCikisi = 25,
        ckDevirUnvXXXXXXneIhtiyacFazlasiDevir = 26,
        ckDevirUnvXXXXXXneStokFazlasiDevir = 27,
        ck663KHKyaDevir = 28,
        ckTuketimYatanHastaTedavisi = 29,
        ckTuketimAyaktaTedaviAcilServis = 30,
        ckTuketimGunuBirlikTedaviAcilServis = 31,
        ckTuketimProtokolHizmeti = 32,
        ckMiadUzatimiCikis = 33,
        ckBagliSaglikTesislerineDevir = 34,
        ckKamuOzelXXXXXXAantidotAntidoksinSatisi = 35,
        skHalkSagligiBagliBirimlereCikis = 36,
        ckTuketimEvdeSaglik = 37,
        ckBirlikiciSaglikTesisineDevir = 38,
        ckSaglikTesisindenGenelSekreterligeDevir = 39,
        ckGarantiVeyaSigortaKapsamindaCikis = 40,
        ckEmanetCikis = 41,
        ckEmanetIade = 42,
        ckPgdCikisi = 43,
        ckDevirDigerKamuIdarelerineDevirCikisi = 44,
        ckDevirKurumlarArasiDevirCikisi = 45,
        ck669KHKDevirCikisi = 46,
        ck667KHKIadeCikisi = 47,
        ckTedarikPaylasim = 48,
        ckDevirMilliSavunmaBakanligiMsbCikisi = 49,
        ck694KHKDevirCikis = 50,
        ckProjeKapsamindaCikis = 51,
        ckKullanimaVermeEvdeBakim = 52,
        ckMucbirDevirTedarikPaylasim = 53,
        ckDevirSaglikMarketDevir = 54,
        ckUniversiteGoturuBedelProtokoluDevirCikis = 55,
        ckHibeBarisGucu = 56,
        ckKullanimaVermeGeciciTahsis = 57,
        ckDevirIcisleriBakanligiProtokolDevirCikis = 58
    }
}