namespace TTObjectClasses
{
    public enum MKYS_ETedarikTurEnum : int
    {
        satinalma = 0,
        takas = 1,
        duzeltme = 2,
        icImkanlarlaUretim = 3,
        tasfiyeIdaresindenEdinilen = 4,
        sayimFazlasi = 5,
        iadeEdilen = 6,
        devirAlinan = 7,
        bagisVeYardim = 8,
        temelSagliktanDevir = 9,
        XXXXXXBirlesmesindenDevir = 10,
        koordinatorXXXXXXdenDevir = 11,
        stokFazlasiDevir = 12,
        ihtiyacFazlasiDevir = 13,
        ambarlarArasiDevir = 14,
        acilisFiiliSayim = 15,
        novartisHibe = 16,
        ilOzelIdaresindenDevirAlinan = 17,
        universiteXXXXXXndenIhtiyacFazlasiDevir = 18,
        universiteXXXXXXndenStokFazlasiDevir = 19,
        KHKdanDevirAlinan = 20,
        MiadUzatimi = 21,
        bagliBirliktenDevir = 22,
        birlikSaglikTesisineDevir = 23,
        bagliSaglikTsisisndenDevir = 24,
        garantiSigortaKapsamindaGiris = 25,
        XXXXXXAndidotAntidoksinGiris = 26,
        devirKurumlarArasiDevir = 27,
        devirDigerKamuIdarelerineDevirGiris = 28,
        devir667KHKDevir = 29,
        devir669KHKDevir = 30,
        tedarikPaylasimDevirGiris = 31,
        hudutSahillerindenDevir = 32,
        hibeProje = 33,
        kamuOzelIsBirligi6428SayiliKanun = 34,
        devir694KHKDevir = 35,
        hibeSihhatProje = 36,
        devirMucbirDevirTedarikPaylasim = 37,
        pgd = 38,
        devirSaglikMarketDevir = 39,
        devirGeciciTahsisDevir = 40,
        hibeBarisGucu = 41,
        sgkTarafindanTedarikEdilenUrun = 42,
        devirCovid19DevirAlinan = 50,
        covid19Satinalma = 51
    }
}