//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuleChecker.Engine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RuleChecker.Engine.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; bu hizmeti girebilmek için aşağıdaki işlemlerden biri girilmiş olmalıdır:
        ///{1}.
        /// </summary>
        public static string BirlikteFaturalandirmaUyarisi {
            get {
                return ResourceManager.GetString("BirlikteFaturalandirmaUyarisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; bu hizmet &quot;{1}&quot; ile birlikte faturalanamaz.
        /// </summary>
        public static string BirlikteFaturalanmazMesaji {
            get {
                return ResourceManager.GetString("BirlikteFaturalanmazMesaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; bu hizmet sadece aşağıdaki branşlardan birine girilmeli: {1}.
        /// </summary>
        public static string BransUygunDegil {
            get {
                return ResourceManager.GetString("BransUygunDegil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; bu hizmet sadece cinsiyeti {1} olan hastalara girilebilir..
        /// </summary>
        public static string CinsiyetSinirlamasiUyarisi {
            get {
                return ResourceManager.GetString("CinsiyetSinirlamasiUyarisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; bu hizmetle birlikte listesi verilen tanılardan biri gerekliydi, lütfen uygun tanıyı ekleyiniz..
        /// </summary>
        public static string GerekliTaniBulunamadi {
            get {
                return ResourceManager.GetString("GerekliTaniBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; bu hizmet için bunlardan birini girebilirsiniz: {1}.
        /// </summary>
        public static string IliskiliTanimUyarisi {
            get {
                return ResourceManager.GetString("IliskiliTanimUyarisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; bu hizmet için {1} koşulunda {2} adet ile sınırlandırılmıştır, lütfen kontrol ediniz.
        /// </summary>
        public static string KosulluIslemTekrariUyarisi {
            get {
                return ResourceManager.GetString("KosulluIslemTekrariUyarisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; bu hizmet için ömür boyu yapılabilme sınırı aşıldı.
        /// </summary>
        public static string OmurBoyuAdetGecildi {
            get {
                return ResourceManager.GetString("OmurBoyuAdetGecildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; bu paket &quot;{1}&quot;. girişi en az &quot;{2}&quot; ay ara ile girilebilir.
        /// </summary>
        public static string OrtodontiMinimumPaketGecildi {
            get {
                return ResourceManager.GetString("OrtodontiMinimumPaketGecildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; bu hizmet ömür boyu bir defa verilebilir..
        /// </summary>
        public static string OrtodontiPaketGirisYapilamaz {
            get {
                return ResourceManager.GetString("OrtodontiPaketGirisYapilamaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; bu hizmet için {1} gün içinde max {2} adet yapılabilir sınırı aşıldı.
        /// </summary>
        public static string SureBoyuAdetGecildi {
            get {
                return ResourceManager.GetString("SureBoyuAdetGecildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; bu hizmet için tedavi boyunca yapılabilecek adet geçildi.
        /// </summary>
        public static string TedaviBoyuAdetGecildi {
            get {
                return ResourceManager.GetString("TedaviBoyuAdetGecildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; bu hizmet için &quot;{1} ay&quot; ila &quot;{2} ay&quot; yaş sınırı belirlenmiş, bu hasta yaşı ({3}) bu sınırında dışında.
        /// </summary>
        public static string YasSiniriAsildi {
            get {
                return ResourceManager.GetString("YasSiniriAsildi", resourceCulture);
            }
        }
    }
}
