namespace TTObjectClasses
{
    public enum DPDetailedErrorTypes : int
    {
        EPISODENULL = 0,
        EPISODE_PATIENTNULL = 1,
        PROCEDUREDOCTORNULL = 2,
        PROCEDUREDOCTOR_PERSONNULL = 3,
        PROCEDUREDOCTOR_PERSON_UNIQUEREFNONULL = 4,
        PROCEDUREOBJECTNULL = 5,
        PROCEDUREOBJECT_GILCODENULLOREMPTY = 6,
        AMOUNTNULL = 7,
        PERFORMEDDATENULL = 8,
        SUBEPISODENULL = 9,
        SUBEPISODE_SPECIALITYNULL = 10,
        SUBEPISODE_SPECIALITY_CODENULLOREMPTY = 11,
        SUBACTIONPROCEDURENULL = 12
    }
}