namespace TTObjectClasses
{
    public enum SMSTypeEnum : int
    {
        Other = 0,
        BulkSMS = 1,
        ChemotherapyRadiotherapy = 2,
        FTRSessionCompleted = 3,
        TreatmentDischargeInfo = 4,
        BirthDaySMS = 5,
        NewPersonnelJoinSMS = 6,
        LeaveJobPersonnelSMS = 7,
        DiagnosisCountInfoSMS = 8,
        ExamDelaySMSForChief = 9,
        ExamDelaySMSForDoctor = 10,
        PathologyReportDelaySMSForChief = 11,
        PathologyReportDelaySMSForForDoctor = 12,
        RadiologyReportDelaySMSForChief = 13,
        RadiologyReportDelaySMSForDoctor = 14,
        EmergencyInterventionSMSForChief = 15,
        EmergencyInterventionSMSForDoctor = 16,
        UnReportedSurgerySMS = 17,
        PathologyDelaySMSForResponsible = 18,
        ExamDelaySMSForResponsible = 19,
        RadiologyReportDelaySMSForResponsible = 20,
        WorkHealthSecWarnSMS = 21,
        MaterialMinimumLevelSMS = 22,
        MaterialSafetyLevelSMS = 23,
        OlayAfetBilgisiSMS = 24,
        SurgeryCompletedSMS = 25,
        ConsultationRequestSMS = 26,
        LaboratoryTakingSampleDelaySMS = 27,
        RadiologyDelaySMS = 28,
        BabyObstetricInfoSMS = 29,
        RadTestReportSMSForPatient = 30,
        RadAppointmentSMSForPatient = 31,
        InpatientInfoSMS = 32,
        PathologyReportSMSForPatient = 33,
        GlassReportSMSForPatient = 34,
        AppointmentInfoSMS = 36,
        VaccineActiveSMSForPatient = 37,
        DiagnosisSMSForPatient = 38
    }
}