export enum FieldTypeEnum {
    Unknown = 0,
    String = 1,
    MultiLineString = 2,
    Script = 3,
    XML = 4,
    GridColumns = 5,
    TabPages = 6,
    ListDefs = 7,
    DataTypes = 8,
    DataMembers = 9,
    ToolStripItems = 10,
    ListViewColumns = 11,
    NQL = 12,
    ReportProperties = 13,
    ReportParameters = 14,
    ReportFieldDefaults = 15,
    ReportShapeDefaults = 16,
    ReportRTFDefaults = 17,
    ByteArray = 18
}