//$25405404
import { BaseViewModel } from "NebulaClient/Model/BaseViewModel";
import { NuclearMedicine } from "NebulaClient/Model/AtlasClientModel";
import { NucMedTreatmentMat } from "NebulaClient/Model/AtlasClientModel";
import { NucMedRadPharmMatGrid } from "NebulaClient/Model/AtlasClientModel";
import { SurgeryDirectPurchaseGrid } from "NebulaClient/Model/AtlasClientModel";
import { RadyofarmasotikDirectPurchaseGrid } from "NebulaClient/Model/AtlasClientModel";
import { DirectPurchaseGrid } from "NebulaClient/Model/AtlasClientModel";
import { DiagnosisGrid } from "NebulaClient/Model/AtlasClientModel";
import { Material } from "NebulaClient/Model/AtlasClientModel";
import { MalzemeTuru } from "NebulaClient/Model/AtlasClientModel";
import { OzelDurum } from "NebulaClient/Model/AtlasClientModel";
import { RadioPharmaceuticalUnitDefinition } from "NebulaClient/Model/AtlasClientModel";
import { DPADetailFirmPriceOffer } from "NebulaClient/Model/AtlasClientModel";
import { ProductDefinition } from "NebulaClient/Model/AtlasClientModel";
import { DirectPurchaseActionDetail } from "NebulaClient/Model/AtlasClientModel";
import { ResUser } from "NebulaClient/Model/AtlasClientModel";
import { Episode } from "NebulaClient/Model/AtlasClientModel";
import { DiagnosisDefinition } from "NebulaClient/Model/AtlasClientModel";
import { Patient } from "NebulaClient/Model/AtlasClientModel";

export class NuclearMedicineApproveFormViewModel extends BaseViewModel {
    public _NuclearMedicine: NuclearMedicine = new NuclearMedicine();
    public GridNuclearMedicineMaterialGridList: Array<NucMedTreatmentMat> = new Array<NucMedTreatmentMat>();
    public ttgrid2GridList: Array<NucMedRadPharmMatGrid> = new Array<NucMedRadPharmMatGrid>();
    public SurgeryDirectPurchaseGridsGridList: Array<SurgeryDirectPurchaseGrid> = new Array<SurgeryDirectPurchaseGrid>();
    public NuclearMedicine_RadyofarmasotikDirectPurchaseGridsGridList: Array<RadyofarmasotikDirectPurchaseGrid> = new Array<RadyofarmasotikDirectPurchaseGrid>();
    public DirectPurchaseGridsGridList: Array<DirectPurchaseGrid> = new Array<DirectPurchaseGrid>();
    public GridEpisodeDiagnosisGridList: Array<DiagnosisGrid> = new Array<DiagnosisGrid>();
    public Materials: Array<Material> = new Array<Material>();
    public MalzemeTurus: Array<MalzemeTuru> = new Array<MalzemeTuru>();
    public OzelDurums: Array<OzelDurum> = new Array<OzelDurum>();
    public RadioPharmaceuticalUnitDefinitions: Array<RadioPharmaceuticalUnitDefinition> = new Array<RadioPharmaceuticalUnitDefinition>();
    public DPADetailFirmPriceOffers: Array<DPADetailFirmPriceOffer> = new Array<DPADetailFirmPriceOffer>();
    public ProductDefinitions: Array<ProductDefinition> = new Array<ProductDefinition>();
    public DirectPurchaseActionDetails: Array<DirectPurchaseActionDetail> = new Array<DirectPurchaseActionDetail>();
    public ResUsers: Array<ResUser> = new Array<ResUser>();
    public Episodes: Array<Episode> = new Array<Episode>();
    public DiagnosisDefinitions: Array<DiagnosisDefinition> = new Array<DiagnosisDefinition>();
    public Patients: Array<Patient> = new Array<Patient>();
}
