using System;
using System.Collections.Generic;
using System.Linq;
using TTDataDictionary;
using TTObjectClasses;

namespace Core.Models
{
    public class InvoiceTermDto
    {
        public Guid ObjectID
        {
            get;
            set;
        }

        public string Name
        {
            get;
            set;
        }

        public DateTime? StartDate
        {
            get;
            set;
        }

        public DateTime? EndDate
        {
            get;
            set;
        }

        public string StateDisplayText
        {
            get;
            set;
        }
    }

    public class InvoiceTermFormViewModel
    {
        public InvoiceTermDto[] InvoiceTermList
        {
            get;
            set;
        }
    }

    public class InvoiceCollectionDto
    {
        public int ? Capacity
        {
            get;
            set;
        }

        public DateTime? Date
        {
            get;
            set;
        }

        public InvoiceCollectionDetail.ChildInvoiceCollectionDetailCollection InvoiceCollectionDetails
        {
            get;
            set;
        }

        public InvoiceTerm InvoiceTerm
        {
            get;
            set;
        }

        public bool ? IsAutoGenerated
        {
            get;
            set;
        }

        public DateTime? LastStateDate
        {
            get;
            set;
        }

        public string LastStateUser
        {
            get;
            set;
        }

        public string Name
        {
            get;
            set;
        }

        public long ? No
        {
            get;
            set;
        }

        public PayerDefinition Payer
        {
            get;
            set;
        }

        //public Currency FaturaTutari { get; set; }
        public Currency DrugTotal
        {
            get;
            set;
        }

        public Currency MaterialTotal
        {
            get;
            set;
        }

        public Currency ProcedureTotal
        {
            get;
            set;
        }

        public int FaturaSayisi
        {
            get;
            set;
        }

        public string StateDisplayText
        {
            get;
            set;
        }

        public Currency InvoicePrice
        {
            get;
            set;
        }

        public Currency Deduction
        {
            get;
            set;
        }

        public Currency PaymentPrice
        {
            get;
            set;
        }

        public Guid? ObjectID
        {
            get;
            set;
        }
    }

    public class InvoiceTermFormDetailViewModel
    {
        public Currency ProcedureTotal
        {
            get;
            set;
        }

        //public Currency FaturaTutari { get; set; }
        public Currency DrugTotal
        {
            get;
            set;
        }

        public Currency MaterialTotal
        {
            get;
            set;
        }

        public int FaturaSayisi
        {
            get;
            set;
        }

        public string SonIslemiYapan
        {
            get;
            set;
        }

        public DateTime LastUpdateDate
        {
            get;
            set;
        }

        public Currency InvoicePrice
        {
            get;
            set;
        }

        public InvoiceCollectionDto[] InvoiceCollectionList
        {
            get;
            set;
        }
    }
}