
using System;
using System.Xml;
using System.Data;
using System.Text;
using System.Drawing;
using System.Reflection;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Collections.ObjectModel;
using System.Runtime.InteropServices;

using TTUtils;
using TTObjectClasses;
using TTDataDictionary;
using TTCoreDefinitions;
using TTConnectionManager;
using TTInstanceManagement;
using TTDefinitionManagement;
using TTStorageManager.Security;

using TTStorageManager;
using System.Runtime.Versioning;
using System.Windows.Forms;
using TTVisual;
namespace TTFormClasses
{
    /// <summary>
    /// BaseHizmetKayitForm
    /// </summary>
    public partial class BaseHizmetKayitForm : BaseMedulaActionForm
    {
    /// <summary>
    /// Hizmet Kayıt
    /// </summary>
        protected TTObjectClasses.HizmetKayit _HizmetKayit
        {
            get { return (TTObjectClasses.HizmetKayit)_ttObject; }
        }

        protected ITTTabControl tttabcontrol1;
        protected ITTTabPage ameliyatveGirisimBilgileriTabpage;
        protected ITTGrid ameliyatveGirisimBilgileriAmeliyatveGirisimBilgisiDVO;
        protected ITTDateTimePickerColumn islemTarihiDateTimeAmeliyatveGirisimBilgisiDVO;
        protected ITTTextBoxColumn islemTarihiAmeliyatveGirisimBilgisiDVO;
        protected ITTListBoxColumn sutKoduAmeliyatveGirisimBilgisiDVO;
        protected ITTTextBoxColumn adetAmeliyatveGirisimBilgisiDVO;
        protected ITTListBoxColumn bransKoduAmeliyatveGirisimBilgisiDVO;
        protected ITTListBoxColumn drTescilNoAmeliyatveGirisimBilgisiDVO;
        protected ITTListDefComboBoxColumn ayniFarkliKesiAmeliyatveGirisimBilgisiDVO;
        protected ITTListDefComboBoxColumn sagSolAmeliyatveGirisimBilgisiDVO;
        protected ITTListDefComboBoxColumn euroscoreAmeliyatveGirisimBilgisiDVO;
        protected ITTTextBoxColumn aciklamaAmeliyatveGirisimBilgisiDVO;
        protected ITTListDefComboBoxColumn ozelDurumAmeliyatveGirisimBilgisiDVO;
        protected ITTTextBoxColumn hizmetSunucuRefNoAmeliyatveGirisimBilgisiDVO;
        protected ITTTextBoxColumn islemSiraNoAmeliyatveGirisimBilgisiDVO;
        protected ITTDateTimePickerColumn CreationDateAmeliyatveGirisimBilgisiDVO;
        protected ITTTabPage muayeneBilgisiTabpage;
        protected ITTLabel labelozelDurumBaseHizmetKayitDVO;
        protected ITTListDefComboBox ozelDurumBaseHizmetKayitDVO;
        protected ITTButton createMuayeneBilgisi;
        protected ITTLabel labelsutKoduMuayeneBilgisiDVO;
        protected ITTValueListBox sutKoduMuayeneBilgisiDVO;
        protected ITTLabel labeldrTescilNoMuayeneBilgisiDVO;
        protected ITTValueListBox drTescilNoMuayeneBilgisiDVO;
        protected ITTLabel labelbransKoduMuayeneBilgisiDVO;
        protected ITTValueListBox bransKoduMuayeneBilgisiDVO;
        protected ITTDateTimePicker muayeneTarihiDateTimeMuayeneBilgisiDVO;
        protected ITTLabel labelmuayeneTarihiMuayeneBilgisiDVO;
        protected ITTTabPage digerIslemBilgileriTabpage;
        protected ITTGrid digerIslemBilgileriDigerIslemBilgisiDVO;
        protected ITTDateTimePickerColumn islemTarihiDateTimeDigerIslemBilgisiDVO;
        protected ITTTextBoxColumn islemTarihiDigerIslemBilgisiDVO;
        protected ITTListBoxColumn sutKoduDigerIslemBilgisiDVO;
        protected ITTTextBoxColumn adetDigerIslemBilgisiDVO;
        protected ITTListBoxColumn bransKoduDigerIslemBilgisiDVO;
        protected ITTListBoxColumn drTescilNoDigerIslemBilgisiDVO;
        protected ITTTextBoxColumn raporTakipNoDigerIslemBilgisiDVO;
        protected ITTListDefComboBoxColumn ozelDurumDigerIslemBilgisiDVO;
        protected ITTTextBoxColumn hizmetSunucuRefNoDigerIslemBilgisiDVO;
        protected ITTTextBoxColumn islemSiraNoDigerIslemBilgisiDVO;
        protected ITTDateTimePickerColumn CreationDateDigerIslemBilgisiDVO;
        protected ITTTabPage disBilgileriTabpage;
        protected ITTGrid disBilgileriDisBilgisiDVO;
        protected ITTDateTimePickerColumn islemTarihiDateTimeDisBilgisiDVO;
        protected ITTTextBoxColumn islemTarihiDisBilgisiDVO;
        protected ITTListBoxColumn sutKoduDisBilgisiDVO;
        protected ITTTextBoxColumn adetDisBilgisiDVO;
        protected ITTListBoxColumn bransKoduDisBilgisiDVO;
        protected ITTListBoxColumn drTescilNoDisBilgisiDVO;
        protected ITTTextBoxColumn sagAltCeneDisBilgisiDVO;
        protected ITTTextBoxColumn solAltCeneDisBilgisiDVO;
        protected ITTTextBoxColumn sagUstCeneDisBilgisiDVO;
        protected ITTTextBoxColumn solUstCeneDisBilgisiDVO;
        protected ITTTextBoxColumn sagSutAltCeneDisBilgisiDVO;
        protected ITTTextBoxColumn solSutAltCeneDisBilgisiDVO;
        protected ITTTextBoxColumn sagSutUstCeneDisBilgisiDVO;
        protected ITTTextBoxColumn solSutUstCeneDisBilgisiDVO;
        protected ITTTextBoxColumn anomaliDisBilgisiDVO;
        protected ITTListDefComboBoxColumn ozelDurumDisBilgisiDVO;
        protected ITTTextBoxColumn hizmetSunucuRefNoDisBilgisiDVO;
        protected ITTTextBoxColumn islemSiraNoDisBilgisiDVO;
        protected ITTDateTimePickerColumn CreationDateDisBilgisiDVO;
        protected ITTTabPage ilacBilgileriTabpage;
        protected ITTGrid ilacBilgileriIlacBilgisiDVO;
        protected ITTDateTimePickerColumn islemTarihiDateTimeIlacBilgisiDVO;
        protected ITTTextBoxColumn islemTarihiIlacBilgisiDVO;
        protected ITTListBoxColumn barkodIlacBilgisiDVO;
        protected ITTListDefComboBoxColumn ilacTuruIlacBilgisiDVO;
        protected ITTTextBoxColumn adetIlacBilgisiDVO;
        protected ITTTextBoxColumn tutarIlacBilgisiDVO;
        protected ITTListDefComboBoxColumn paketHaricIlacBilgisiDVO;
        protected ITTTextBoxColumn aciklamaIlacBilgisiDVO;
        protected ITTListDefComboBoxColumn ozelDurumIlacBilgisiDVO;
        protected ITTTextBoxColumn hizmetSunucuRefNoIlacBilgisiDVO;
        protected ITTTextBoxColumn islemSiraNoIlacBilgisiDVO;
        protected ITTDateTimePickerColumn CreationDateIlacBilgisiDVO;
        protected ITTTabPage konsultasyonBilgileriTabpage;
        protected ITTGrid konsultasyonBilgileriKonsultasyonBilgisiDVO;
        protected ITTDateTimePickerColumn islemTarihiDateTimeKonsultasyonBilgisiDVO;
        protected ITTTextBoxColumn islemTarihiKonsultasyonBilgisiDVO;
        protected ITTListBoxColumn sutKoduKonsultasyonBilgisiDVO;
        protected ITTListBoxColumn bransKoduKonsultasyonBilgisiDVO;
        protected ITTListBoxColumn drTescilNoKonsultasyonBilgisiDVO;
        protected ITTListDefComboBoxColumn ozelDurumKonsultasyonBilgisiDVO;
        protected ITTTextBoxColumn hizmetSunucuRefNoKonsultasyonBilgisiDVO;
        protected ITTTextBoxColumn islemSiraNoKonsultasyonBilgisiDVO;
        protected ITTDateTimePickerColumn CreationDateKonsultasyonBilgisiDVO;
        protected ITTTabPage malzemeBilgileriTabpage;
        protected ITTGrid malzemeBilgileriMalzemeBilgisiDVO;
        protected ITTDateTimePickerColumn islemTarihiDateTimeMalzemeBilgisiDVO;
        protected ITTTextBoxColumn islemTarihiMalzemeBilgisiDVO;
        protected ITTTextBoxColumn barkodMalzemeBilgisiDVO;
        protected ITTTextBoxColumn malzemeKoduMalzemeBilgisiDVO;
        protected ITTListDefComboBoxColumn malzemeTuruMalzemeBilgisiDVO;
        protected ITTTextBoxColumn adetMalzemeBilgisiDVO;
        protected ITTTextBoxColumn kodsuzMalzemeAdiMalzemeBilgisiDVO;
        protected ITTTextBoxColumn kodsuzMalzemeFiyatiMalzemeBilgisiDVO;
        protected ITTListDefComboBoxColumn katkiPayiMalzemeBilgisiDVO;
        protected ITTListDefComboBoxColumn paketHaricMalzemeBilgisiDVO;
        protected ITTListDefComboBoxColumn ozelDurumMalzemeBilgisiDVO;
        protected ITTTextBoxColumn hizmetSunucuRefNoMalzemeBilgisiDVO;
        protected ITTTextBoxColumn islemSiraNoMalzemeBilgisiDVO;
        protected ITTDateTimePickerColumn CreationDateMalzemeBilgisiDVO;
        protected ITTTabPage tahlilBilgileriTabpage;
        protected ITTGrid tahlilBilgileriTahlilBilgisiDVO;
        protected ITTDateTimePickerColumn islemTarihiDateTimeTahlilBilgisiDVO;
        protected ITTTextBoxColumn islemTarihiTahlilBilgisiDVO;
        protected ITTListBoxColumn sutKoduTahlilBilgisiDVO;
        protected ITTTextBoxColumn adetTahlilBilgisiDVO;
        protected ITTListBoxColumn bransKoduTahlilBilgisiDVO;
        protected ITTListBoxColumn drTescilNoTahlilBilgisiDVO;
        protected ITTListDefComboBoxColumn ozelDurumTahlilBilgisiDVO;
        protected ITTTextBoxColumn hizmetSunucuRefNoTahlilBilgisiDVO;
        protected ITTTextBoxColumn islemSiraNoTahlilBilgisiDVO;
        protected ITTDateTimePickerColumn CreationDateTahlilBilgisiDVO;
        protected ITTTabPage tanilarTabpage;
        protected ITTGrid tanilarTaniBilgisiDVO;
        protected ITTListBoxColumn taniKoduTaniBilgisiDVO;
        protected ITTListDefComboBoxColumn taniTipiTaniBilgisiDVO;
        protected ITTListDefComboBoxColumn birincilTaniTaniBilgisiDVO;
        protected ITTListDefComboBoxColumn ozelDurumTaniBilgisiDVO;
        protected ITTTextBoxColumn hizmetSunucuRefNoTaniBilgisiDVO;
        protected ITTTextBoxColumn islemSiraNoTaniBilgisiDVO;
        protected ITTDateTimePickerColumn CreationDateTaniBilgisiDVO;
        protected ITTTabPage tetkikveRadyolojiBilgileriTabpage;
        protected ITTGrid tetkikveRadyolojiBilgileriTetkikveRadyolojiBilgisiDVO;
        protected ITTDateTimePickerColumn islemTarihiDateTimeTetkikveRadyolojiBilgisiDVO;
        protected ITTTextBoxColumn islemTarihiTetkikveRadyolojiBilgisiDVO;
        protected ITTListBoxColumn sutKoduTetkikveRadyolojiBilgisiDVO;
        protected ITTTextBoxColumn adetTetkikveRadyolojiBilgisiDVO;
        protected ITTListBoxColumn bransKoduTetkikveRadyolojiBilgisiDVO;
        protected ITTListBoxColumn drTescilNoTetkikveRadyolojiBilgisiDVO;
        protected ITTListDefComboBoxColumn ozelDurumTetkikveRadyolojiBilgisiDVO;
        protected ITTTextBoxColumn aciklamaTetkikveRadyolojiBilgisiDVO;
        protected ITTTextBoxColumn hizmetSunucuRefNoTetkikveRadyolojiBilgisiDVO;
        protected ITTTextBoxColumn islemSiraNoTetkikveRadyolojiBilgisiDVO;
        protected ITTDateTimePickerColumn CreationDateTetkikveRadyolojiBilgisiDVO;
        protected ITTTabPage hastaYatisBilgileriTabpage;
        protected ITTGrid hastaYatisBilgileriHastaYatisBilgisiDVO;
        protected ITTDateTimePickerColumn yatisBaslangicTarihiDateTimeHastaYatisBilgisiDVO;
        protected ITTDateTimePickerColumn yatisBitisTarihiDateTimeHastaYatisBilgisiDVO;
        protected ITTTextBoxColumn yatisBaslangicTarihiHastaYatisBilgisiDVO;
        protected ITTTextBoxColumn yatisBitisTarihiHastaYatisBilgisiDVO;
        protected ITTListBoxColumn sutKoduHastaYatisBilgisiDVO;
        protected ITTListBoxColumn bransKoduHastaYatisBilgisiDVO;
        protected ITTListBoxColumn drTescilNoHastaYatisBilgisiDVO;
        protected ITTTextBoxColumn refakatciGunSayisiHastaYatisBilgisiDVO;
        protected ITTListDefComboBoxColumn ozelDurumHastaYatisBilgisiDVO;
        protected ITTTextBoxColumn hizmetSunucuRefNoHastaYatisBilgisiDVO;
        protected ITTTextBoxColumn islemSiraNoHastaYatisBilgisiDVO;
        protected ITTDateTimePickerColumn CreationDateHastaYatisBilgisiDVO;
        protected ITTTextBox takipNoHizmetKayitGirisDVO;
        protected ITTTextBox hastaBasvuruNoHizmetKayitGirisDVO;
        protected ITTLabel labeltakipNoHizmetKayitGirisDVO;
        protected ITTLabel labelsaglikTesisKoduHizmetKayitGirisDVO;
        protected ITTValueListBox saglikTesisKoduHizmetKayitGirisDVO;
        protected ITTLabel labelhastaBasvuruNoHizmetKayitGirisDVO;
        override protected void InitializeControls()
        {
            tttabcontrol1 = (ITTTabControl)AddControl(new Guid("eaa0a42e-3837-49ab-bc26-67f552587ec9"));
            ameliyatveGirisimBilgileriTabpage = (ITTTabPage)AddControl(new Guid("e1863497-e4a8-4715-aedc-d6ba4f31383f"));
            ameliyatveGirisimBilgileriAmeliyatveGirisimBilgisiDVO = (ITTGrid)AddControl(new Guid("1fbb5abe-a9d9-449a-8d17-196e9eadb9e6"));
            islemTarihiDateTimeAmeliyatveGirisimBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("eed2a2f0-796d-4539-b6dc-9d0e502ec4ec"));
            islemTarihiAmeliyatveGirisimBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("99848eb5-3a74-40d6-a802-a9b5614e0c26"));
            sutKoduAmeliyatveGirisimBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("6b33a895-7fd8-4a85-9a61-b3eaf5837087"));
            adetAmeliyatveGirisimBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("47162cd5-3075-4fb3-ba35-7571e48d140c"));
            bransKoduAmeliyatveGirisimBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("a82d04fa-3ff8-4861-a271-0008a5eb2d9a"));
            drTescilNoAmeliyatveGirisimBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("21ad16df-fdbe-49da-8dd1-74e027a3d105"));
            ayniFarkliKesiAmeliyatveGirisimBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("50812d54-48a5-472e-8162-6c2e66da016c"));
            sagSolAmeliyatveGirisimBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("59454fb8-0f03-4592-bd7b-d910cf4620d6"));
            euroscoreAmeliyatveGirisimBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("dcb5bac5-f916-4a44-8d96-46c9beb39f81"));
            aciklamaAmeliyatveGirisimBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("de8e19f2-285f-44e2-bfa5-3516f1f790f8"));
            ozelDurumAmeliyatveGirisimBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("45f583b3-d6e7-41df-bcc6-19eacfda2aff"));
            hizmetSunucuRefNoAmeliyatveGirisimBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("013925e8-f2b5-4e89-9f8a-463663ed7acd"));
            islemSiraNoAmeliyatveGirisimBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("d75c49c4-3247-40be-9605-8dd945315e87"));
            CreationDateAmeliyatveGirisimBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("c4c2a7c6-254a-4245-9369-ae63ff4af61e"));
            muayeneBilgisiTabpage = (ITTTabPage)AddControl(new Guid("af7acb3b-b3b4-4096-a910-c33fa80afc75"));
            labelozelDurumBaseHizmetKayitDVO = (ITTLabel)AddControl(new Guid("0935db00-cac7-4efe-afb3-59b9975bbe2f"));
            ozelDurumBaseHizmetKayitDVO = (ITTListDefComboBox)AddControl(new Guid("22409ad1-0c53-4038-80f6-153b90751b42"));
            createMuayeneBilgisi = (ITTButton)AddControl(new Guid("f760f4a2-0941-4680-bef6-a8c84234ade2"));
            labelsutKoduMuayeneBilgisiDVO = (ITTLabel)AddControl(new Guid("7490e812-8092-4543-baba-36d9a9366216"));
            sutKoduMuayeneBilgisiDVO = (ITTValueListBox)AddControl(new Guid("a5432b05-14c7-474c-bb82-69b9ef4bd57b"));
            labeldrTescilNoMuayeneBilgisiDVO = (ITTLabel)AddControl(new Guid("84397079-98db-4a45-860b-3ce23baec481"));
            drTescilNoMuayeneBilgisiDVO = (ITTValueListBox)AddControl(new Guid("66ffcbaa-1499-4b06-bdd8-3c5cc52f6fe6"));
            labelbransKoduMuayeneBilgisiDVO = (ITTLabel)AddControl(new Guid("d3123eef-ace5-42f3-b970-c7771fa5c291"));
            bransKoduMuayeneBilgisiDVO = (ITTValueListBox)AddControl(new Guid("e13e9227-960b-4101-8ccc-cd17c5fac6db"));
            muayeneTarihiDateTimeMuayeneBilgisiDVO = (ITTDateTimePicker)AddControl(new Guid("c5918172-7270-4842-b412-f9b3f7b07934"));
            labelmuayeneTarihiMuayeneBilgisiDVO = (ITTLabel)AddControl(new Guid("840a4bda-bc21-41aa-a1e0-9286fc89ad39"));
            digerIslemBilgileriTabpage = (ITTTabPage)AddControl(new Guid("4925d0e4-c64e-4fd9-994a-6750048a44d9"));
            digerIslemBilgileriDigerIslemBilgisiDVO = (ITTGrid)AddControl(new Guid("6efd4677-2c72-43d4-9508-93f0d7d5226f"));
            islemTarihiDateTimeDigerIslemBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("0d204dc8-fd75-44a4-b7df-a75b6a2c9a62"));
            islemTarihiDigerIslemBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("56d9149f-b45e-430b-8fef-bc5f52cbbd2a"));
            sutKoduDigerIslemBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("224e8b41-c16b-46cd-a5c1-1849a56154b1"));
            adetDigerIslemBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("4a6c835f-c364-4677-9afe-aadfc9278eb9"));
            bransKoduDigerIslemBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("e41f2283-c406-48de-ba6e-20a49cdae096"));
            drTescilNoDigerIslemBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("5decb61f-ab80-4d44-8b80-8b32e8d3a5a8"));
            raporTakipNoDigerIslemBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("e3e40ae4-b84c-4de8-8bf2-144087e17bdd"));
            ozelDurumDigerIslemBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("a87a54fd-4f96-4dad-8be7-aa1b93e6a256"));
            hizmetSunucuRefNoDigerIslemBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("b2a2c6fc-0118-44ea-b723-bb893aa5fb86"));
            islemSiraNoDigerIslemBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("7d8a5522-bf36-4762-9009-7af4596b84a7"));
            CreationDateDigerIslemBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("52ca44db-b32c-418f-9458-c978d469cdd0"));
            disBilgileriTabpage = (ITTTabPage)AddControl(new Guid("afd08e9f-0e1b-4599-8c04-127a3300bec9"));
            disBilgileriDisBilgisiDVO = (ITTGrid)AddControl(new Guid("46a4e2bd-2307-4438-8913-aa58c31829f3"));
            islemTarihiDateTimeDisBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("343b25b0-3b9d-4f67-a19b-2f4f8a3e655e"));
            islemTarihiDisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("861faccb-619f-4cef-bd17-672880fe232c"));
            sutKoduDisBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("c15926fb-272c-4fb6-9fd6-bdf4e28bbc2b"));
            adetDisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("f4ad954b-27e6-4708-9f13-7b1ed6a319eb"));
            bransKoduDisBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("e7adbf21-06a0-408f-a492-ffb52aabba49"));
            drTescilNoDisBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("35b9c8d5-7c4c-4db3-a1c2-07e2c2b9d9a6"));
            sagAltCeneDisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("6d108a69-f9f4-4aab-b306-b968ce0e2704"));
            solAltCeneDisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("79a429a4-6c88-41bb-83fb-8a306365f0fa"));
            sagUstCeneDisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("a81d736b-84c0-4ad6-a77b-37f57483c3ac"));
            solUstCeneDisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("98f4f9ac-4b7f-48d4-adff-0455c31214c7"));
            sagSutAltCeneDisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("d3cb9098-3987-48fd-a3d7-fe9bc28acb86"));
            solSutAltCeneDisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("825dc460-991a-4db7-ada0-61b0f83ba214"));
            sagSutUstCeneDisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("1d309a80-3dfa-4368-abfa-762b0d41bb7a"));
            solSutUstCeneDisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("d77f226c-6646-45e0-a0a5-d89d62adb6f7"));
            anomaliDisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("238adb09-d076-4732-ae6f-2d5edeebe019"));
            ozelDurumDisBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("c181320a-9952-4292-a59a-6b57c68bb861"));
            hizmetSunucuRefNoDisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("a12dcd1f-81c6-4fb8-993e-7c2d14779773"));
            islemSiraNoDisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("d2006662-872c-440a-87f4-2508d545df15"));
            CreationDateDisBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("ef49747b-5f84-431a-b01b-81d8c5e28134"));
            ilacBilgileriTabpage = (ITTTabPage)AddControl(new Guid("19163083-6b9b-4ecc-b9ee-efdb72c0b567"));
            ilacBilgileriIlacBilgisiDVO = (ITTGrid)AddControl(new Guid("0209269f-3b90-403f-bce2-4f072c4a2d1b"));
            islemTarihiDateTimeIlacBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("712e3c3a-34ac-43a0-9fcf-bf3205d9e1f7"));
            islemTarihiIlacBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("0e0d5870-2872-47d6-ae3a-e2da7d372e8e"));
            barkodIlacBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("aa305d74-4feb-4c04-b071-2324b7f4d30e"));
            ilacTuruIlacBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("98d70421-afc6-4047-8260-d8957489ed62"));
            adetIlacBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("9b1f48ba-1c6b-4908-b1e1-3c768a0d289f"));
            tutarIlacBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("ad3e65c3-e203-44a0-8313-84bf2c96594e"));
            paketHaricIlacBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("2afff934-f4ab-466d-8199-ea614d7dbbcb"));
            aciklamaIlacBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("34ee760b-e528-4ba9-a165-8b23e48dc1e4"));
            ozelDurumIlacBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("5b29b002-a8be-4cd0-a263-fac9845f7d92"));
            hizmetSunucuRefNoIlacBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("e146058b-ce31-4836-b8f1-0b11976d9856"));
            islemSiraNoIlacBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("5a6e3ece-1136-483c-84d8-85eea6a51331"));
            CreationDateIlacBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("6f74fbd0-0051-4eb1-844a-62b6176740d8"));
            konsultasyonBilgileriTabpage = (ITTTabPage)AddControl(new Guid("43dec2f6-2532-4272-8453-be87ec37dd3f"));
            konsultasyonBilgileriKonsultasyonBilgisiDVO = (ITTGrid)AddControl(new Guid("0419e85f-678c-4be2-86fc-3a2eab8b5910"));
            islemTarihiDateTimeKonsultasyonBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("1335a362-df01-459a-96b5-10d99fc6cd7d"));
            islemTarihiKonsultasyonBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("20c0612c-f25b-4770-9a2a-6b2ca4d3e321"));
            sutKoduKonsultasyonBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("71a8aebe-dc8b-4431-8fff-15028706f875"));
            bransKoduKonsultasyonBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("5bf449a8-e105-49df-bb33-9646f0521925"));
            drTescilNoKonsultasyonBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("10131923-3315-4be3-9142-20d24a2f6a8b"));
            ozelDurumKonsultasyonBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("5755be20-e0b9-4725-8be1-cd294620f424"));
            hizmetSunucuRefNoKonsultasyonBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("0ebcf3e5-903b-4f3f-8c9c-4f9c83c9bf6d"));
            islemSiraNoKonsultasyonBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("887fcd51-daf2-409e-8138-422e3cd25b20"));
            CreationDateKonsultasyonBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("5b0dc90c-6cc5-4763-839a-4916bcf318fc"));
            malzemeBilgileriTabpage = (ITTTabPage)AddControl(new Guid("16f4d02a-22d8-41cd-9a48-800a88771cfe"));
            malzemeBilgileriMalzemeBilgisiDVO = (ITTGrid)AddControl(new Guid("608fe231-03fe-4dab-8dd6-2b57827297d1"));
            islemTarihiDateTimeMalzemeBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("4de07c93-f7e0-4ae6-8ed1-efe65beb0dac"));
            islemTarihiMalzemeBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("fc091ebd-f831-40cc-8694-2a6f7eebd146"));
            barkodMalzemeBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("7499a178-0bed-4b07-9531-63f6154b8302"));
            malzemeKoduMalzemeBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("840250d5-28fc-44b7-a52f-e523137ba5e1"));
            malzemeTuruMalzemeBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("695f9cd4-3e65-4c8d-ba1c-7d2140afb52a"));
            adetMalzemeBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("6774dc48-e576-4304-87ad-4e73ee838dfe"));
            kodsuzMalzemeAdiMalzemeBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("3fd13cb4-27d4-43d8-8044-75f82f3f52ab"));
            kodsuzMalzemeFiyatiMalzemeBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("5d41e3f7-8665-4c28-9742-953cf44df064"));
            katkiPayiMalzemeBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("88eedb3d-f298-421f-bfd7-963c6c69c64a"));
            paketHaricMalzemeBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("35c84d35-0640-48e3-9b1f-c14bfb925afc"));
            ozelDurumMalzemeBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("81982763-bbc3-4094-b3f0-7b468dae1657"));
            hizmetSunucuRefNoMalzemeBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("444b09af-034a-4721-8a69-c44b22aab5a0"));
            islemSiraNoMalzemeBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("67990f3e-1b8e-4b95-994c-de8616eea768"));
            CreationDateMalzemeBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("7e2d627e-c1f3-47de-98e1-99f8273aa4e0"));
            tahlilBilgileriTabpage = (ITTTabPage)AddControl(new Guid("3d7508aa-3ec1-4d9a-b4cc-34c96d85d0c3"));
            tahlilBilgileriTahlilBilgisiDVO = (ITTGrid)AddControl(new Guid("719d1a2e-65e4-41f4-9c95-b99bb630553b"));
            islemTarihiDateTimeTahlilBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("6c43c1f2-5a51-413e-807a-34db87bc8eef"));
            islemTarihiTahlilBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("92fc0dd4-7c14-45df-a1f4-d6e1c8b6f42a"));
            sutKoduTahlilBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("5b2b2d19-6a3d-4840-a5d5-04065db21c01"));
            adetTahlilBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("2e5c2eee-e460-43da-bb29-74cee1ef9195"));
            bransKoduTahlilBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("8c67d99f-6156-4939-a8ea-23eaaa435a40"));
            drTescilNoTahlilBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("e102683d-62b6-450b-9750-6f86ea02ca7b"));
            ozelDurumTahlilBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("f2bee63f-3020-45ea-aa86-830a7e92c95d"));
            hizmetSunucuRefNoTahlilBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("271ef08b-29bf-4005-9920-27a8b28058ab"));
            islemSiraNoTahlilBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("de30b13c-aa61-4cc0-8efe-0a6cce87145e"));
            CreationDateTahlilBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("9ddb0c14-2317-4be9-bbc9-e3464f9bc8be"));
            tanilarTabpage = (ITTTabPage)AddControl(new Guid("56418770-f2a7-4f64-b269-aff028819a12"));
            tanilarTaniBilgisiDVO = (ITTGrid)AddControl(new Guid("4d2d3301-7906-4bb1-b90f-734d928dbc7e"));
            taniKoduTaniBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("50968e1d-ca79-4feb-bd6a-70c0a9adeadc"));
            taniTipiTaniBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("35d8a32f-c19c-4dbb-b31e-f314ab91a5e0"));
            birincilTaniTaniBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("0144ebb6-c06e-4bae-98d9-ee69b31298c1"));
            ozelDurumTaniBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("087dd34d-ab4c-42b5-95b7-6b871507e3a9"));
            hizmetSunucuRefNoTaniBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("fed31220-ac59-43ab-a99d-cc15179230ce"));
            islemSiraNoTaniBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("ca3a39bd-f670-4d75-aed8-8a619c2f418a"));
            CreationDateTaniBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("d39ad0c9-0ec6-4bc1-b5be-eab6d65d33b2"));
            tetkikveRadyolojiBilgileriTabpage = (ITTTabPage)AddControl(new Guid("35f2fa17-7513-4da1-888e-382e1ddcb952"));
            tetkikveRadyolojiBilgileriTetkikveRadyolojiBilgisiDVO = (ITTGrid)AddControl(new Guid("c3291f23-34bf-4e89-857e-f4fc57d9637a"));
            islemTarihiDateTimeTetkikveRadyolojiBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("f5b59303-8ee9-4a48-9c22-173f7e851d81"));
            islemTarihiTetkikveRadyolojiBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("f74bbbd0-e2f4-46c5-986c-997ffc6652b8"));
            sutKoduTetkikveRadyolojiBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("9a54949a-d7b9-458a-b48d-09409800c9c9"));
            adetTetkikveRadyolojiBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("1757ba38-9d05-49d9-b91a-d8128f8cec13"));
            bransKoduTetkikveRadyolojiBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("dcdf0484-746a-42ca-85a1-b15d274a5537"));
            drTescilNoTetkikveRadyolojiBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("8901b374-ef36-4e04-9b17-723dacfe9343"));
            ozelDurumTetkikveRadyolojiBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("8447d1ce-cbab-4047-9f24-12ae9108d169"));
            aciklamaTetkikveRadyolojiBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("e69f83dd-3347-45c1-9023-67e1cf532893"));
            hizmetSunucuRefNoTetkikveRadyolojiBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("1d6d6b50-e87c-4a45-bb5c-5dd626d59ce9"));
            islemSiraNoTetkikveRadyolojiBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("315ff780-76a9-4118-b45e-e4ccf18a4b47"));
            CreationDateTetkikveRadyolojiBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("f600b5a2-9e45-47ae-a73b-decc84196dbd"));
            hastaYatisBilgileriTabpage = (ITTTabPage)AddControl(new Guid("35686985-226c-4dcd-8dc5-20decda1c5f6"));
            hastaYatisBilgileriHastaYatisBilgisiDVO = (ITTGrid)AddControl(new Guid("88916281-7958-4df0-ac32-767c39f3c4f5"));
            yatisBaslangicTarihiDateTimeHastaYatisBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("a2ae531e-b4f1-4974-aeb3-11bd020522ca"));
            yatisBitisTarihiDateTimeHastaYatisBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("2d37075a-2a47-4a35-bd3a-eb68137b0341"));
            yatisBaslangicTarihiHastaYatisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("0abaf51a-36b7-48bb-8f5b-a6efc73c4d03"));
            yatisBitisTarihiHastaYatisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("fbfb3bc8-6bb8-4749-a907-6a81013c68ce"));
            sutKoduHastaYatisBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("f7ceaa3f-e75a-48dc-a053-56074f8f1ffb"));
            bransKoduHastaYatisBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("454f1f9f-2063-46fa-aee1-48b9ee3a4860"));
            drTescilNoHastaYatisBilgisiDVO = (ITTListBoxColumn)AddControl(new Guid("94b54668-005c-46a4-a7ae-9ea46dd90b1d"));
            refakatciGunSayisiHastaYatisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("a5c062bd-1014-4b4c-b382-ffde4beb40c3"));
            ozelDurumHastaYatisBilgisiDVO = (ITTListDefComboBoxColumn)AddControl(new Guid("6a798cb8-559e-44ab-94c1-4e48467b7b9e"));
            hizmetSunucuRefNoHastaYatisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("7d2ae4f0-aa5c-4595-8297-5292c71c9ece"));
            islemSiraNoHastaYatisBilgisiDVO = (ITTTextBoxColumn)AddControl(new Guid("487ab38d-315e-420c-98c0-fe52b3272aa0"));
            CreationDateHastaYatisBilgisiDVO = (ITTDateTimePickerColumn)AddControl(new Guid("de769e37-bf23-4138-8063-6ce478537f76"));
            takipNoHizmetKayitGirisDVO = (ITTTextBox)AddControl(new Guid("42bbba84-5f8d-4e69-a77d-d96c3aaca997"));
            hastaBasvuruNoHizmetKayitGirisDVO = (ITTTextBox)AddControl(new Guid("693dcb99-f302-414e-b16a-6a9c9d6c9209"));
            labeltakipNoHizmetKayitGirisDVO = (ITTLabel)AddControl(new Guid("880905ae-25be-4319-a6ee-02db9c8e9163"));
            labelsaglikTesisKoduHizmetKayitGirisDVO = (ITTLabel)AddControl(new Guid("264f81a5-170b-43cc-b5ff-4eb7d4ee32a2"));
            saglikTesisKoduHizmetKayitGirisDVO = (ITTValueListBox)AddControl(new Guid("cd87464c-983e-4b9c-814c-95f44456e588"));
            labelhastaBasvuruNoHizmetKayitGirisDVO = (ITTLabel)AddControl(new Guid("ddb563f9-bc8c-4d85-a36a-fa5e4a1e2f6a"));
            base.InitializeControls();
        }

        public BaseHizmetKayitForm() : base("HIZMETKAYIT", "BaseHizmetKayitForm")
        {
        }

        protected BaseHizmetKayitForm(string objectDefName, string formDefName) : base(objectDefName, formDefName)
        {
        }
    }
}