namespace TTObjectClasses
{
    public enum MKYS_EOlcuBirimEnum : int
    {
        adet = 0,
        ampul = 1,
        bag = 2,
        blister = 3,
        boy = 4,
        bolum = 5,
        bidon = 6,
        cilt = 7,
        desimetreKare = 8,
        desimetreKup = 9,
        doz = 10,
        duzine = 11,
        flakon = 12,
        galon = 13,
        gram = 14,
        kapsul = 15,
        kartus = 16,
        kasa = 17,
        kavanoz = 18,
        koli = 19,
        kutu = 20,
        kilogram = 21,
        kisi = 22,
        litre = 23,
        metre = 24,
        metreKare = 25,
        metreKup = 26,
        metreTul = 27,
        miliGram = 28,
        miliLitre = 29,
        paket = 30,
        plaka = 31,
        poset = 32,
        rulo = 33,
        santiMetre = 34,
        santiMetreKare = 35,
        ster = 36,
        tabaka = 37,
        tablet = 38,
        takim = 39,
        teneke = 40,
        ton = 41,
        top = 42,
        torba = 43,
        tup = 44,
        cift = 45,
        unite = 46,
        sise = 47,
        test = 48,
        mci = 49,
        kwh = 50,
        set = 51,
        mikgrogram = 52,
        puan = 53,
        kart = 54,
        kova = 55,
        draje = 56,
        enjektor = 57,
        makara = 58,
        disk = 59
    }
}