namespace TTObjectClasses
{
    public enum MKYS_EGirisStokHareketTurEnum : int
    {
        grSatinAlinanMalzemeninGirisi = 0,
        grBirimlerdenGelenMalzemeGirisi = 1,
        grBirimlerdenIade = 2,
        grSayimFazlasi = 3,
        grYilSonuDevri = 4,
        grIadeEdilen = 5,
        grIcImkanlarlaUretilen = 6,
        grTasfiyeIdaresindenEdinilen = 7,
        grBagisHibe = 8,
        grAmbarlarArasiDevir = 9,
        grDuzetme = 10,
        grTakas = 11,
        grIhtiyacFazlasiGirisi = 12,
        grStokFazlasiGirisi = 13,
        grKoordinatorXXXXXXdenDevirAlinan = 14,
        grXXXXXXBirlesmesindenDevir = 15,
        grTemelSagliktanDevir = 16,
        grHibeProje = 17,
        grNovartisHibe = 18,
        grilOzelIdaresindenDevir = 19,
        grUnvXXXXXXndenStokFazlasiDevirGirisi = 20,
        grUnvXXXXXXndenIhtiyacFazlasiDevirGirisi = 21,
        gr663KHKdanDevirGirisi = 22,
        grMiadUzatimiGiris = 23,
        grBagliBirliktenDevirGirisi = 24,
        grBirlikSaglikTesisineDevir = 25,
        grSaglikTesisindenGenelSekreterligeDevir = 26,
        grGarantiVeyaSigortaKApsamindaGiris = 27,
        grSatinalinanKamuOZelXXXXXXAntidotAntidoksinCikis = 28,
        grDevirKurumlarArasiDevirGirisi = 29,
        grDevirDigerKamuIdarelerineDevirGiris = 30,
        gr667KHKDevir = 31,
        gr669KHKDevir = 32,
        grHudutSahillerindenDevirGirisi = 33,
        grTedarikPaylasim = 34,
        grKamuOzelIsBirligi6428SayiliKanun = 35,
        gr694KHKDevir = 36,
        grHibeSihhatProje = 37,
        grMucbirDevirTedarikPaylasim = 38,
        grPgdGirisi = 39,
        grDevirSaglikMarketDevir = 40,
        grHibeBarisGucu = 41,
        grSgkTarafindanTedarikEdilenUrun = 42
    }
}