using System;
using System.Collections.Generic;
using TTObjectClasses;

namespace AtlasModel
{
    public partial class SocServAppliedProcedures
    {
        public Guid ObjectId { get; set; }
        public bool? ProvidingAccomodation { get; set; }
        public bool? ProvideInternalSecInjStatDoc { get; set; }
        public bool? ProvisionIssues { get; set; }
        public bool? WeeklyTeamMeetings { get; set; }
        public bool? WeeklyVisitAttendence { get; set; }
        public bool? CalcAndFollowRestProc { get; set; }
        public bool? InformAndDirectRetireProc { get; set; }
        public bool? MedicEqProcRefundInfoProcure { get; set; }
        public bool? DonatedMedicalSupplyProcure { get; set; }
        public bool? GuidanceOnDrugSupplyAbroad { get; set; }
        public bool? BenefitingFromDonations { get; set; }
        public bool? GuidanceToFoundations { get; set; }
        public bool? GuidanceToCivilOrganizations { get; set; }
        public bool? GuidanceAboutCareSalary { get; set; }
        public bool? GuidanceAboutLaw { get; set; }
        public bool? GuidanceAboutHomeHealthCare { get; set; }
        public bool? PhoneCallWitPublicInstitution { get; set; }
        public bool? LegislativeReviewAndInfo { get; set; }
        public bool? GuidanceToPublicInstitution { get; set; }
        public bool? CoordWarVeteranContactUnit { get; set; }
        public bool? ArrangementOfLivingPlaces { get; set; }
        public bool? ArrangementOfWorkSchoolEnv { get; set; }
        public bool? IntraCityTransportProcesses { get; set; }
        public bool? InterCityTransportProcesses { get; set; }
        public bool? IdentificationOfParticipants { get; set; }
        public bool? OrganizingPermitDocuments { get; set; }
        public bool? HealthAid { get; set; }
        public bool? AdvancePayment { get; set; }
        public bool? IndemnityCompensation { get; set; }
        public bool? AllowancePayment { get; set; }
        public bool? GivingVeteranRightsBrochure { get; set; }
        public bool? CashIdemnityTransactions { get; set; }
        public bool? XXXXXXSolidarityFoundationAid { get; set; }
        public bool? SoldierFoundationAid { get; set; }
        public bool? SoldierLifeInsurance { get; set; }
        public bool? OYAKAid { get; set; }
        public bool? JobResumeStatus { get; set; }
        public bool? StatePrideMedal { get; set; }
        public bool? SalaryStartBySGK { get; set; }
        public bool? RetirementBonusBySGK { get; set; }
        public bool? SupplementaryPaymentSGK { get; set; }
        public bool? EducationAidBySGK { get; set; }
        public bool? GrantingEmploymentRights { get; set; }
        public bool? ProvidingWarVeteranCard { get; set; }
        public bool? UtilizationOfPublicHousing { get; set; }
        public bool? ProvideHouseToDisabledStaff { get; set; }
        public bool? GivingCorporateHousingCredit { get; set; }
        public bool? UsageRightFromTOKIHouses { get; set; }
        public bool? IncomeTaxDiscount { get; set; }
        public bool? ResidenceTaxExemption { get; set; }
        public bool? ElectricAndWaterDiscount { get; set; }
        public bool? ImportingDutyFreeVehicle { get; set; }
        public bool? DomesticVehiclePurchases { get; set; }
        public bool? OTVandMTVExemption { get; set; }
        public bool? BrotherExemptionFromMilitary { get; set; }
        public bool? MilitaryServiceNearBrotherHom { get; set; }
        public bool? FreeAccessToPrivateEduInstit { get; set; }
        public bool? WeaponPortageTransportLicense { get; set; }
        public string ProvidingAccomodationInfo { get; set; }
        public string ProvideInterSecInjStatDocInfo { get; set; }
        public string ProvisionIssuesInfo { get; set; }
        public string WeeklyTeamMeetingsInfo { get; set; }
        public string WeeklyVisitAttendenceInfo { get; set; }
        public string CalcAndFollowRestProcInfo { get; set; }
        public string InformAndDirectRetireProcInfo { get; set; }
        public string MedicEqProcRefundInfoProcInfo { get; set; }
        public string DonatedMedicalSupplyProcInfo { get; set; }
        public string GuidanceDrugSupplyAbroadInfo { get; set; }
        public string GuidanceToCivilOrganizatInfo { get; set; }
        public string GuidanceToFoundationsInfo { get; set; }
        public string BenefitingFromDonationsInfo { get; set; }
        public string GuidanceAboutCareSalaryInfo { get; set; }
        public string GuidanceAboutLawInfo { get; set; }
        public string GuidanceAboutHomeHealthCrInfo { get; set; }
        public string PhoneCallWitPublicInstitInfo { get; set; }
        public string LegislativeReviewAndInfoInfo { get; set; }
        public string GuidanceToPublicInstitInfo { get; set; }
        public string CoordWarVeteranContactUniInfo { get; set; }
        public string ArrangementOfLivingPlacesInfo { get; set; }
        public string ArrangementOfWorkSchoolEnInfo { get; set; }
        public string IntraCityTransportProcessInfo { get; set; }
        public string InterCityTransportProcessInfo { get; set; }
        public string IdentificationOfParticipInfo { get; set; }
        public bool? UtilityFromRehabilitationCent { get; set; }
        public bool? GrantingDealership { get; set; }
        public string OpenEducationHighSchool { get; set; }
        public string Other { get; set; }
        public string GuidanceServiceOnPhone { get; set; }
        public string AdvancePaymentInfo { get; set; }
        public string IndemnityCompensationInfo { get; set; }
        public string OrganizingPermitDocumentsInfo { get; set; }
        public string HealthAidInfo { get; set; }
        public string AllowancePaymentInfo { get; set; }
        public string GivingVeteranRightsBrocInfo { get; set; }
        public string CashIdemnityTransactionsInfo { get; set; }
        public string XXXXXXSolidarityFoundatioAidInfo { get; set; }
        public string SoldierFoundationAidInfo { get; set; }
        public string SoldierLifeInsuranceInfo { get; set; }
        public string OYAKAidInfo { get; set; }
        public string JobResumeStatusInfo { get; set; }
        public string StatePrideMedalInfo { get; set; }
        public string SalaryStartBySGKInfo { get; set; }
        public string RetirementBonusBySGKInfo { get; set; }
        public string SupplementaryPaymentSGKInfo { get; set; }
        public string EducationAidBySGKInfo { get; set; }
        public string GrantingEmploymentRightsInfo { get; set; }
        public string ProvidingWarVeteranCardInfo { get; set; }
        public string UtilizationOfPublicHousinInfo { get; set; }
        public string ProvideHouseToDisablStaffInfo { get; set; }
        public string GivingCorporateHousCreditInfo { get; set; }
        public string UsageRightFromTOKIHousesInfo { get; set; }
        public string IncomeTaxDiscountInfo { get; set; }
        public string ResidenceTaxExemptionInfo { get; set; }
        public string ElectricAndWaterDiscountInfo { get; set; }
        public string ImportingDutyFreeVehicleInfo { get; set; }
        public string DomesticVehiclePurchasesInfo { get; set; }
        public string OTVandMTVExemptionInfo { get; set; }
        public string BrotherExemptionFromMilitInfo { get; set; }
        public string MilitarServNearBrotherHomInfo { get; set; }
        public string FreeAccessToPrivEduInstitInfo { get; set; }
        public string WeaponPortageTransportLicInfo { get; set; }
        public string UtilityFromRehabilitCentInfo { get; set; }
        public string GrantingDealershipInfo { get; set; }
        public string VocationalRehabilitationInfo { get; set; }
        public bool? VocationalRehabilitation { get; set; }
    }
}