//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTestConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RuleCheckStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RuleCheckStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceTestConsole.RuleCheckStrings", typeof(RuleCheckStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate any instances of contract {0}.
        /// </summary>
        internal static string CannotLocateInstancesOfContract {
            get {
                return ResourceManager.GetString("CannotLocateInstancesOfContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUT kural listesi önbelleğe alınıyor....
        /// </summary>
        internal static string InitializeCacheStarted {
            get {
                return ResourceManager.GetString("InitializeCacheStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adet SUT tanımı önbelleğe alındı.
        /// </summary>
        internal static string ProcedureCacheInitialized {
            get {
                return ResourceManager.GetString("ProcedureCacheInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adet SUT kural önbelleğe alındı.
        /// </summary>
        internal static string RuleCacheInitialized {
            get {
                return ResourceManager.GetString("RuleCacheInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUT Kural servisi {0} portu üzerinde başlatıldı.
        /// </summary>
        internal static string ServiceStartCompleted {
            get {
                return ResourceManager.GetString("ServiceStartCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUT Kural servisi başlatılıyor....
        /// </summary>
        internal static string ServiceStarting {
            get {
                return ResourceManager.GetString("ServiceStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUT Kural service durduruldu..
        /// </summary>
        internal static string ServiceStopCompleted {
            get {
                return ResourceManager.GetString("ServiceStopCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUT Kural servisi durduruluyor....
        /// </summary>
        internal static string ServiceStopStarted {
            get {
                return ResourceManager.GetString("ServiceStopStarted", resourceCulture);
            }
        }
    }
}
